// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortener.Services.Database.Data;

#nullable disable

namespace URLShortener.WebApi.Migrations
{
    [DbContext(typeof(UrlShortenerDbContext))]
    [Migration("20251226211302_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URLShortener.Services.Database.Entities.AboutPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("AboutPages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "This URL Shortener uses Base62 encoding...",
                            CreatedDate = new DateTime(2025, 12, 26, 21, 13, 2, 107, DateTimeKind.Utc).AddTicks(1933),
                            LastModified = new DateTime(2025, 12, 26, 21, 13, 2, 107, DateTimeKind.Utc).AddTicks(2001)
                        });
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("AccountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "Regular"
                        });
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClickCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShortenedURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("OriginalURL")
                        .IsUnique();

                    b.ToTable("URLs");
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountTypeId = 1,
                            NickName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEO0XYX+Sr3p2dYUwuAiuLadWwW4lhR14HWgrDG5inI30B6UmlXlNB06gSjo97jeibg==",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.AboutPage", b =>
                {
                    b.HasOne("URLShortener.Services.Database.Entities.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.Url", b =>
                {
                    b.HasOne("URLShortener.Services.Database.Entities.User", "Creator")
                        .WithMany("URLs")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.User", b =>
                {
                    b.HasOne("URLShortener.Services.Database.Entities.AccountType", "AccountType")
                        .WithMany("Users")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.AccountType", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("URLShortener.Services.Database.Entities.User", b =>
                {
                    b.Navigation("URLs");
                });
#pragma warning restore 612, 618
        }
    }
}
